//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buscket
    {
        public int Id { get; set; }
        public int User { get; set; }
        public int Item { get; set; }
    
        public virtual Item Item1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
