//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Recipe
    {
        public int Id { get; set; }
        public int Item { get; set; }
        public int Recipe { get; set; }
    
        public virtual Item Item1 { get; set; }
        public virtual Recipe Recipe1 { get; set; }
    }
}
